Adding new feature to YAML archive test push

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -14,4 +14,9 @@ jobs:
     - name: Install dependencies
       run: npm install
     - name: Run Jasmine tests
-      run: npm test
+      run: | 
+        npm test
+        if[$? -eq 3]; then
+          echo "Test failed. Push rejected."
+          exit 1
+        fi 
